import json
from pathlib import Path
from datetime import datetime


class SimReporter:
    def __init__(self, base_path="reports/master"):
        self.base = Path(base_path)
        self.base.mkdir(parents=True, exist_ok=True)

    def generate(self, run_id: str, summary: dict):
        run_dir = self.base / run_id
        run_dir.mkdir(parents=True, exist_ok=True)

        # JSON export
        with open(run_dir / "summary.json", "w") as f:
            json.dump(summary, f, indent=2)

        # HTML report
        html = f"""
        <html>
        <head><title>Ryuzen TestOps Report — {run_id}</title></head>
        <body style='font-family:Arial; padding:20px;'>
            <h1>Ryuzen Toron v2.5H+ — TestOps Report</h1>
            <h3>Run ID: {run_id}</h3>
            <p><strong>Date:</strong> {datetime.utcnow().isoformat()}Z</p>
            <hr>
            <h2>Summary Metrics</h2>
            <ul>
                <li><strong>Average Latency:</strong> {summary.get("avg_latency_ms")} ms</li>
                <li><strong>P95 Latency:</strong> {summary.get("p95_latency_ms")} ms</li>
                <li><strong>Average Confidence:</strong> {summary.get("avg_confidence")}</li>
                <li><strong>Total Runs:</strong> {summary.get("total_runs")}</li>
            </ul>
            <h2>Flag Counts</h2>
            <pre>{json.dumps(summary.get("flag_counts", {}), indent=2)}</pre>
            <hr>
            <p>Generated by Ryuzen TestOps Suite.</p>
        </body>
        </html>
        """

        with open(run_dir / "report.html", "w", encoding="utf-8") as f:
            f.write(html)

        return {"path": str(run_dir)}
