services:
  nexus:
    image: ${CI_IMAGE_REF:?CI_IMAGE_REF not set}
    env_file:
      - .env.ci
    environment:
      PORT: ${PORT:-8080}
    ports:
      - "8080:${PORT:-8080}"
    healthcheck:
      test: ["CMD-SHELL", "for p in /health /healthz /status /readyz /; do curl -fsS http://127.0.0.1:${PORT:-8080}$p && exit 0; done; exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s
