version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
  nexus:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NEXUS_RATE_LIMIT_STORAGE_URL=redis://redis:6379/0
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=4
    depends_on:
      - redis
    ports:
      - "8443:8443"
