name: k6-smoke
on:
  workflow_call:
    inputs:
      base_url: { required: true, type: string }

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: ./k6/smoke.js
        env:
          BASE_URL: ${{ inputs.base_url }}
