import { QueryClient } from "@tanstack/react-query";
import { nanoid } from "nanoid";

import { useUIStore, type LibraryItem } from "@/shared/state/ui";

export const queryClient = new QueryClient();

const latency = async (duration = 250) =>
  new Promise((resolve) => {
    setTimeout(resolve, duration);
  });

export async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? "GET").toUpperCase();

  if (path === "/library" && method === "GET") {
    await latency(120);
    const items = useUIStore.getState().libraryItems;
    return { items } as T;
  }

  if (path === "/library/dummy-study-pack" && method !== "GET") {
    await latency(320);
    const item: LibraryItem = {
      id: nanoid(),
      title: "Study Pack — " + new Date().toLocaleDateString(),
      summary: "A curated set of prompts and flashcards generated by Nexus.",
      createdAt: new Date().toISOString(),
    };
    useUIStore.getState().addLibraryItem(item);
    return { success: true, item } as T;
  }

  await latency(120);
  return { success: true } as T;
}
