import { QueryClient } from "@tanstack/react-query";
import { nanoid } from "nanoid";

import { logEvent } from "@/shared/lib/audit";
import { retryWithBackoff } from "@/shared/lib/retry";
import { track } from "@/shared/lib/analytics";
import { useUIStore, type LibraryItem } from "@/shared/state/ui";

export const queryClient = new QueryClient();

const latency = async (duration = 250) =>
  new Promise((resolve) => {
    setTimeout(resolve, duration);
  });

export async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const method = (init?.method ?? "GET").toUpperCase();

  if (path === "/chat/reply") {
    const body = init?.body ? JSON.parse(init.body as string) : {};
    const userMessage: string = body?.message ?? "";
    return retryWithBackoff(async () => {
      await latency(600);
      const reply = {
        role: "assistant" as const,
        content: `Here’s a verified response to: “${userMessage}”`,
        citations: [
          { title: "Example Source", url: "https://example.com" },
          { title: "Second Ref", url: "https://example2.com" },
        ],
      };
      track("chat:reply", { length: userMessage.length });
      return reply as T;
    });
  }

  if (path === "/library" && method === "GET") {
    await latency(120);
    const items = useUIStore.getState().libraryItems;
    return { items } as T;
  }

  if (path === "/library/dummy-study-pack" && method !== "GET") {
    await latency(320);
    const item: LibraryItem = {
      id: nanoid(),
      title: `Study Pack — ${new Intl.DateTimeFormat(navigator.language, {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date())}`,
      summary: "A curated set of prompts and flashcards generated by Nexus.",
      createdAt: new Date().toISOString(),
    };
    useUIStore.getState().addLibraryItem(item);
    logEvent("library:dummy-pack", { id: item.id, title: item.title });
    track("library:created", { id: item.id });
    return { success: true, item } as T;
  }

  await latency(120);
  return { success: true } as T;
}
