"""Execution orchestrator for Toron Engine."""
from __future__ import annotations

import time
from typing import Dict, List

from src.backend.telemetry.telemetry_aggregator import TelemetryAggregator


class Orchestrator:
    """Coordinates data preparation and post-processing."""

    def __init__(self, telemetry: TelemetryAggregator) -> None:
        self.telemetry = telemetry

    def plan(self, prompt: str, context: Dict[str, str] | None = None) -> Dict[str, str]:
        """Create a minimal execution plan for the request."""

        return {
            "mode": "analysis" if context and context.get("analysis") else "chat",
            "prompt_length": len(prompt),
            "context_keys": list(context.keys()) if context else [],
        }

    def finalize_response(self, prompt: str, model: Dict[str, str], transcript: List[str]) -> str:
        """Combine debate output into a single string."""

        summary = " ".join(transcript).strip()
        self.telemetry.record_inference(model_name=model.get("name", "unknown"), prompt=prompt, latency_ms=5)
        return summary or f"Response generated by {model.get('name', 'toron-model')}"

    def audit_trail(self, model: Dict[str, str], steps: List[str]) -> Dict[str, str]:
        """Create an audit entry for observability pipelines."""

        return {
            "model": model.get("name"),
            "steps": steps,
            "timestamp": time.time(),
        }
