name: CD Prod
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy"
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/reusables/k8s-deploy.yml
    with:
      env_name: prod
      namespace: nexus-prod
      image_tag: ${{ inputs.image_tag }}
    secrets:
      K8S_CLUSTER: ${{ secrets.K8S_PROD_CLUSTER }}

  k6:
    needs: deploy
    uses: ./.github/workflows/reusables/k6-smoke.yml
    with:
      base_url: ${{ secrets.PROD_BASE_URL }}
